# Generated by Django 5.1.1 on 2024-09-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('sent_date', models.DateTimeField()),
                ('receiving_date', models.DateTimeField()),
            ],
        ),
    ]
